name: Flatpak

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'flatpak/**'
      - 'images/**'
      - '.github/workflows/flatpak.yml'
      - '.github/workflows/flatpak-reusable.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'flatpak/**'
      - 'images/**'
      - '.github/workflows/flatpak.yml'
      - '.github/workflows/flatpak-reusable.yml'

jobs:
  flatpak:
    uses: ./.github/workflows/flatpak-reusable.yml
